import './globals.scss';
import '@fontsource-variable/chivo';
import localFont from 'next/font/local';
// import Image from 'next/image';
// import Link from 'next/link';
import { ReactNode } from 'react';
import Footer from './components/Footer';
import Header from './components/Header';

const groteskGras = localFont({
  src: './fonts/Grotesk-04Gras.woff',
  variable: '--font-grotesk-gras',
  weight: '900',
});
const groteskMince = localFont({
  src: './fonts/Grotesk-02Mince.woff',
  variable: '--font-grotesk-mince',
  weight: '100',
});
const groteskRegular = localFont({
  src: './fonts/Grotesk-03Regular.woff',
  variable: '--font-grotesk-regular',
  weight: '400',
});
const ddin = localFont({
  src: './fonts/D-DIN.woff',
  variable: '--font-ddin',
  weight: '300',
});
const ddinBold = localFont({
  src: './fonts/D-DIN-Bold.woff',
  variable: '--font-ddin-bold',
  weight: '300',
});

export const metadata = {
  title: {
    default: 'Home | Vector',
    template: '%s | Vector',
  },

  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body
        className={`${groteskGras.variable} ${groteskMince.variable} ${groteskRegular.variable} ${ddin.variable} ${ddinBold.variable}`}
      >
        <div className="w-full">
          <Header />
          <main className="content">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
